package webTests;
// Generated by Selenium IDE
import org.junit.Assert;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
import java.util.concurrent.TimeUnit;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.MatcherAssert.assertThat;

public class SeleniumIDE {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @BeforeMethod
    public void setUp() {
        System.setProperty("webdriver.chrome.driver","drivers/chrome/112/chromedriver.exe"); // Ao exportar o método, é necessário direcionar o caminho do driver
        driver = new ChromeDriver();
        driver.manage().timeouts().implicitlyWait(60000, TimeUnit.MILLISECONDS);
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @AfterMethod
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void consultarPythoneJava() {
        driver.get("https://iterasys.com.br/pt");
        driver.manage().window().setSize(new Dimension(1936, 1056));
        driver.findElement(By.cssSelector("#\\31 6237702146520 > .item-pill")).click();
        driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/main/div/section/div/div/div/div/div/div[2]/div/div/div/input")).click();
        driver.findElement(By.xpath("//input")).sendKeys("Python");
        driver.manage().timeouts().implicitlyWait(60000, TimeUnit.MILLISECONDS);
        Assert.assertThat(driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/main/div/section/div/div/div/div/main/a/main/div/div[2]/p")).getText(), is("R$ 27,90"));
        driver.findElement(By.xpath("//input")).click();
        driver.findElement(By.xpath("//input")).sendKeys("Introdução ao Java");
        driver.manage().timeouts().implicitlyWait(60000, TimeUnit.MILLISECONDS);
        Assert.assertThat(driver.findElement(By.xpath("/html/body/div[1]/div/div/div[1]/main/div/section/div/div/div/div/main/a/main/div/div[2]/p")).getText(), is("R$ 27,90"));
        }
}
// Alterados os caminhos para full xpath, pois o ID é gerado automaticamente. Sendo assim, pelo xpath é possível achar o campo de pesquisa e fazer a execução
// Os caminhos do assertThat foram alterados para o full xpath, pois estavam pegando o primeiro css da página.

